### ISSUE TITLE
Is the documentation of My Calendar Pro outdated?

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar-pro#21]
My Calendar Pro documentation is from June 2020 and does not appear to have been adjusted.
![grafik](https://user-images.githubusercontent.com/96249763/150976949-cbdda29f-4ae7-4a75-b830-099fadfc1777.png)

My active versions: 3.3.5 and 2.1.4

**Text in documentation:**
`[advanced_search date='true' author='true' host='true' category='true' location='true' home='custom URL'] `

It is enough to enter the `[advanced_search]` shortcut without parameters, because I make the settings in the "Advanced Search" tab of My Calendar Pro.

**These questions arise:** 

1. why doesn't my advanced search work? It does not come to the result. (Please test with search word 'critical mass' in my form: https://www.klimabuendnis-hamm.de/kalender/suchen/
2. do the date fields in the advanced search always have to be mandatory fields?
3. like with Generate Shortcodes/Submissions, I want to create the labels myself, because I need them in German.

**Comment by joedolson** [comment]
Is the page you have the shortcode on the same as the page set for advanced search in the Advanced Search tab?

You can disable date fields in the search; that should work. 

Just as a note, GitHub is not a support system, it's an issue tracking system - as such, please try to always add a new issue for every topic raised. There are four separate issues in here, which makes it hard to keep track of where things are.

**Comment by UliMand** [comment]
> Is the page you have the shortcode on the same as the page set for advanced search in the Advanced Search tab?

Yes, it's the same page
![grafik](https://user-images.githubusercontent.com/96249763/151661373-4b06d999-cd94-4cc9-9418-168502769852.png)
![grafik](https://user-images.githubusercontent.com/96249763/151661457-08d764da-3f93-452d-bc9b-f1d10b437cfe.png)

![grafik](https://user-images.githubusercontent.com/96249763/151661397-cecd95f9-0b96-41c4-9660-dcf2d249610e.png)

> You can disable date fields in the search; that should work.

When I disable the date fields, they are missing from the advanced search form.
They should be displayed, but they must not be mandatory fields.

> ... please try to always add a new issue for every topic raised. 

Okay, no problem

**Comment by joedolson** [comment]
The documentation for My Calendar Pro is due an update, yes - I was planning on doing that with the next major release, which is targeted for late spring/early summer.

**Comment by paaljoachim** [comment]
I plan on going through the My Calendar Pro documentation and see what needs to be improved.

**Comment by joedolson** [comment]
Docs have been updated at https://docs.joedolson.com/my-calendar-pro/
