### ISSUE TITLE
Expired event: publish link in my calendar

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar-pro#25]
**Is your feature request related to a problem? Please describe.**
After an event has expired, I write a post with a report about the event. I want to put the post-link in my calendar, because My Calendar becomes an archive of past events after the event.

**Describe the solution you'd like**
I would like to have another field for the post link after event.

**Describe alternatives you've considered**
So far I have to overwrite the "more information" field for this. This is a pity.

**Comment by joedolson** [comment]
This seems like a scenario better handled with custom fields; I've never had requests for this before, and it seems like a requirement with pretty limited scope - not something that a lot of people need. Also, you can always place the link in the content  or description, and that would cover a lot of cases. 

Have you looked at custom fields? https://github.com/joedolson/plugin-extensions/blob/master/my-calendar/my-calendar-custom-fields.php
