### ISSUE TITLE
Space in ics imported files, Summary + Description

### ISSUE THREAD

**Issue by UrsWeberG** [joedolson/my-calendar-pro#26]
![Screenshot 2022-03-12 at 10 41 55](https://user-images.githubusercontent.com/101453303/158012894-74ed4931-03e1-4b75-a52f-34c578591f25.jpg)
**Describe the bug**
If I Import ics files which have more than 75 char per line, then the unfolding of it does not occur properly

**To Reproduce**
Import ics which have more than 75 char in summary or description

**Expected behavior**
not only the \r\n should removed, it should remove the " " or \t too

**Screenshots**
Example: (in mycalendar / in ics)
Astrid Lindgren: Ronja Räubertoch ter, Atze Musiktheater, Thomas Suter
Astrid Lindgren: Ronja Räubertochter, Atze Musiktheater, Thomas Suter

**Desktop (please complete the following information):**
on all

**Additional context**
unfolding should happen according to https://www.loc.gov/preservation/digital/formats/fdd/fdd000394.shtml#:~:text=An%20iCalendar%20file%20consists%20of,as%20defined%20in%20RFC%205234 or  https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php (line 860)

please insert 
"
   $string = implode(PHP_EOL, $lines);
   $string = preg_replace('/' . PHP_EOL . '[ \t]/', '', $string);
   $lines = explode(PHP_EOL, $string);
"
   
public function __construct($filename=false)
{
   if ( ! $filename ) {
      return false;
   }

   if ( is_array( $filename ) ) {
      $lines = $filename;
   } else {
      $lines = file( $filename, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES );
   }

   $string = implode(PHP_EOL, $lines);
   $string = preg_replace('/' . PHP_EOL . '[ \t]/', '', $string);
   $lines = explode(PHP_EOL, $string);

   return $this->initLines( $lines );
}

in wp-content/plugins/my-calendar-pro/classes/class.iCalReader.php  (line 49)

and edit 
//$description = ( isset( $event['DESCRIPTION'] ) ) ? str_replace( PHP_EOL, '', wpautop( $event['DESCRIPTION'] ) ) : '';
to
$description = ( isset( $event['DESCRIPTION'] ) ) ?  $event['DESCRIPTION'] : '';   
in
wp-content/plugins/my-calendar-pro/my-calendar-import.php (line 349)

**Comment by joedolson** [comment]
Thanks for reporting this and suggesting a fix! I'll take a look at it.
