### ISSUE TITLE
Cursor does not change on hovering a clickable link in tabs in My Calendar Pro screen.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar-pro#28]
**Describe the bug**
Testing. Newest My Calendar Pro and My Calendar plugins.

Hovering over the tabs the cursor does not change to a finger signaling the typical clickable cursor type.
![My calendar Pro tabs no change cursor](https://user-images.githubusercontent.com/5323259/166150773-705319d2-942e-43c9-9dec-a68b31401c4a.jpg)

See also this issue:
https://github.com/joedolson/my-calendar/issues/464

**Comment by joedolson** [comment]
Technically, this is correct. It's an ambiguity, however, since technically (according to specs) the finger icon means "link", but is heavily used as a css customization to mean "interactive", resulting in a common expectation that has changed the semantic meaning of the cursor over time.
