### ISSUE TITLE
Consolidating a few of the tabs?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar-pro#31]
**Is your feature request related to a problem? Please describe.**
Can we consolidate the 9 tabs into fewer tabs?

**Describe the solution you'd like**
Submissions
Payments
License
Blog New Events (should be new - small n - similar to Events from Posts)
Events from Posts
Advanced Search 
Responsive
Importer
REST API

What about an Advanced tab to add License, Advanced Search and REST API?

I am working on getting fewer tabs. Making it easier to get an overview. Going down from 9 to perhaps 6-7 tabs.

Original:
![Screenshot 2022-05-01 at 16 57 42](https://user-images.githubusercontent.com/5323259/166151604-d8154e8c-a9f1-4aa8-a840-dfcdd74d18c9.jpg)

Consolidating (adding less used tabs into an Advanced tab.)
![My Calendar Pro Advanced tab](https://user-images.githubusercontent.com/5323259/166151770-e4424517-30fc-4020-b5b1-a7f4edc106ca.jpg)

NB. The various issues are meant to get us to think about various solutions to various things I notice that would be good to look closer at.

**Comment by joedolson** [comment]
The way the Pro extension set up is done, this would be kind of tricky. What I might want to do, instead, is make this into side tabs, so I don't run against space limits as quickly.

Also, I like the fact that each tab represents a unique set of features; if I combined several features into one tab, those features will become harder to locate.

**Comment by paaljoachim** [comment]
Hey Joe

When I look at navigation I look for what is important to add at the top level. 
How many top level items becomes the sweet point before I begin to lose an overview.
Which items can be hidden further down and is not used as much. Which will also lessen the cognitive load.

Side tabs sounds like a better way to handle this as there are quite a number of tabs.

**Comment by paaljoachim** [comment]
Sidebar tabs feels better compared to having the same tabs in the top.
Here is a screenshot of the sidebar tabs.

![Screen Shot 2022-06-08 at 12 21 34](https://user-images.githubusercontent.com/5323259/172593822-731c400c-751f-49d2-8bb2-db9e23887a7f.png)

I will go ahead and close this issue, as moving the top tabs to the sidebar helped.
