### ISSUE TITLE
Payment and other similar tabs: Showing more information before clicking the checkbox.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar-pro#32]
**Is your feature request related to a problem? Please describe.**
Clicking the Payments tab.
There is by default very little information showing.

![Screenshot 2022-05-01 at 17 05 00](https://user-images.githubusercontent.com/5323259/166151929-4c18a187-55a6-4a9c-9749-20bb6459fb68.jpg)

**Describe the solution you'd like**
It would be helpful to add more information here so the user gets a better overview before clicking the checkbox and the Save Payment Settings button. 

After clicking the checkbox and the button to Save Payment Settings we see the Payment Settings, New purchase messages, Pricing, Payment Gateways and Configure a Sale sections.

**Comment by paaljoachim** [comment]
Actually I see the same with Blog New Events and Events from Posts. As these too offer very little information before clicking the checkbox and clicking the blue button to save the settings.

**Comment by joedolson** [comment]
What information would you want to see?

**Comment by paaljoachim** [comment]
I can ask what is in general this section about.
That reply with a few sentences could be a good intro text before one clicks the checkbox to get the detailed view of each.

When a screen has a few words and a checkbox it would be nice with an overview of what I would see when clicking the checkbox. An intro/summary of what will follow.

I can also look into it later on.

**Comment by paaljoachim** [comment]
Great! An intro text has been added to multiple screens.

![Screen Shot 2022-06-08 at 12 14 05](https://user-images.githubusercontent.com/5323259/172592222-489d8867-c193-412d-afee-6d02e3550062.png)

![Screen Shot 2022-06-08 at 12 14 50](https://user-images.githubusercontent.com/5323259/172592467-7f787537-1a76-4483-aea2-79f1360bc9cd.png)

![Screen Shot 2022-06-08 at 12 14 59](https://user-images.githubusercontent.com/5323259/172592545-d0d888f8-957c-4e65-90f0-c53a39c2c5d6.png)

![Screen Shot 2022-06-08 at 12 15 14](https://user-images.githubusercontent.com/5323259/172592591-f354ff0d-2553-493a-87b9-e78da2a92585.png)
