### ISSUE TITLE
Auto create Event Submission and Event Editing pages.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar-pro#34]
**Is your feature request related to a problem? Please describe.**
I am currently exploring the Event Submission Page.

I currently see this:
![Screenshot 2022-05-02 at 12 27 41](https://user-images.githubusercontent.com/5323259/166220553-bedeb58b-8a49-4fe1-8667-c36740a97d07.jpg)

**Describe the solution you'd like**
I would like a simple way to create the Submission and the Event Editing pages.

**Describe alternatives you've considered**

To create the Submission page I went to pages - Add New. 
Added the title Submit events. Then published it.
In All Pages I hovered the title and noticed the Page ID 696 show up in the status bar.
Went back to the Submissions page. Inserted the ID 696 into the Event Submissions Page ID.
Clicked Save Submissions Settings.
Noticed the link Edit "Submit events" show up. 

Repeated the same procedure for the Event Editing Page.

**Comment by joedolson** [comment]
The submit page is already created on installation; but it is only created on a *new* installation, so that could get a bit fuzzy when using reset plugins and re-activating. If you didn't drop tables when you uninstalled, it'll still be considered a re-install, not a new install.
