### ISSUE TITLE
Add form builder

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar-pro#40]
Initial draft of form builder is in https://github.com/joedolson/my-calendar-pro/commit/d45c8168c6a1e4db26e6333cf5a6c80f82f1f32a

- [x] Add ability to group in sections
- [x] Add drag and drop / click to add functionality
- [x] Re-map field edit view to only include labels, 'remove' instead of delete
- [x] Add support for needed category/location fields
- [x] Add support for required location fields

**Comment by joedolson** [comment]
Added management of groups, though not the ability to create new groups. Maybe later; basic framework is there.

**Comment by paaljoachim** [comment]
Hey Joe.
What is the form builder?

**Comment by joedolson** [comment]
New version of the shortcode generator for submissions forms

https://docs.joedolson.com/my-calendar-pro/2023/03/24/generate-shortcodes-submissions-forms/
