### ISSUE TITLE
Clarify that user needs to save after creating new field or add AJAX save

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar-pro#41]
When editing custom fields, the 'Edit Custom Fields' button may be quite distant from the current focus.  Since the field preview updates dynamically, it may not be evident that a save is required. 

Todo:
 - save dynamically or
 - display a close 'edit field' button when form is dirty and
 - Add this screen to the dirty warnings so user is warned when leaving with unsaved changes

**Comment by paaljoachim** [comment]
Hey Joe.

Can you tell me about what this feature is and does?
Thank you.

**Comment by joedolson** [comment]
See https://docs.joedolson.com/my-calendar-pro/category/custom-fields/

This is relevant to how the fields behave when editing the settings for a custom field (last screenshot on that page.)
