### ISSUE TITLE
Other Settings - Turning on and then turning off to disable does not work

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar-pro#53]
I went to Other Settings > Clicked the checkbox to enable "Enable language selector on events"
Noticed that no additional options where added below. I then clicked to disable the same setting and clicked the Update Settings button, but the checkmark came back again into the same checkbox.

Example deselecting both checkboxes and clicking the Update Settings button.
![Disable checkboxes does not work](https://user-images.githubusercontent.com/5323259/227581872-a3afa12e-38ee-47d0-b283-6357a844ac15.gif)

Perhaps it is meant to be this way. If so then a message needs to be seen about not being able to disable these checkboxes.

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/my-calendar-pro/commit/9c6646033d3890293998a27da0a9414dc0f5b600

**Comment by paaljoachim** [comment]
Great it now works!
