### ISSUE TITLE
Doc site: Copy and paste error when using keyboard

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar-pro#54]
I am using the Brave browser.
Copy (ctrl+c) and paste (ctrl+v) the text copied shows up as a link.
Here is an animated gif.

![Copy-Paste-error](https://user-images.githubusercontent.com/5323259/227606092-dcf31f51-0c17-4d46-8e84-99fdfafe096f.gif)

Example used.
Copying from this draft **Settings - Custom Fields**: https://docs.joedolson.com/my-calendar-pro/wp-admin/post.php?post=183&action=edit
into another draft **Settings - Notifications**: https://docs.joedolson.com/my-calendar-pro/wp-admin/post.php?post=181&action=edit

I resaved both drafts and it seemed to work alright this time. I will add more information when I discover a few more hints as to why this might be happening.

**Comment by joedolson** [comment]
That's pretty strange. It's very unlikely that this is anything I can do anything about; it seems like either a browser or a Gutenberg bug, but thanks for the FYI. Were you able to reproduce this with any other browsers?

**Comment by paaljoachim** [comment]
Weird I see the same error in Firefox when copied text from here https://docs.joedolson.com/my-calendar-pro/category/admin/
and into here https://docs.joedolson.com/my-calendar-pro/wp-admin/post.php?post=181&action=edit

The explorations continues as I redo various documentation pages.

**Comment by paaljoachim** [comment]
Closing for now. Can reopen if/when it shows up again.
