### ISSUE TITLE
Creating an event from a post

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar-pro#57]
Let's say...

My Calendar Pro > Events from Posts.
-Checked- Post events from posts
-Checked- Posts. In the **Supported Post Types**

Went to a Post.
A Post has a title and some content.
When writing the Post title it would be nice to also have the My Calendar Event meta box Event Title be filled out at the same time.
Like so. Having the Post title automatically duplicate into the Event Title.

![Screenshot 2023-03-24 at 22 22 28](https://user-images.githubusercontent.com/5323259/227644088-ba27ebd1-14b9-495a-8f9f-9e7c1963192e.jpg)

What about taking content from the block editor canvas/document and have that automatically transfer over to the Event Description (Event Content). I assume I will need to copy the content the best I can from the block editor canvas and over to the Event Description area.

It would be great to have an association between the block editor content and the My Calendar Event content.

**Comment by joedolson** [comment]
I kind of feel that defeats the purpose of having two separate listings - I don't want to generate duplicate content for people if I can avoid it.  The post about the event isn't the event itself, so I don't think it should have either the same title or the same content; if a user does want that, it's not a huge challenge to copy it over.
