### ISSUE TITLE
Feedback on the Advanced Search Page - Page creation

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar-pro#58]
I am looking at the Advanced Search screen.
Before going to the bottom of this screen to click "Save Settings" it looks like this:

![My Calendar Pro Settings Advanced Search](https://user-images.githubusercontent.com/5323259/227647225-d1cf958f-844e-4d5e-9257-b6f1356f5ed5.jpg)

The Submissions screen has two auto generated screens. "Submit Events" and the "Edit Events".

It would be helpful to stick to one method to generate new pages.
About about a generate screen icon or some more direct method to generate a screen?

When additional pages are to be created through the My Calendar plugin. It would be nice to make it obvious for the user so she/he can click a button to generate the page(s) they want. Be it pages on the Submissions tab, Advanced Search tab or elsewhere.

**Comment by joedolson** [comment]
As of 3.0.4, the search page is also created at installation, like the submissions & editing pages. This won't impact existing users, but all pages are now handled the same way.

**Comment by paaljoachim** [comment]
Great. It helps having the search page auto created at installation. Thanks.
