### ISSUE TITLE
Shortcodes > Submission Forms:  Opening locations all fields are pushed at 1140px width or smaller

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar-pro#61]
**Describe the bug**
Opening various fields in the Shortcodes > Submission Forms these will open within the space defined.
![Screenshot 2023-05-03 at 12 05 57](https://user-images.githubusercontent.com/5323259/235888046-c07fafb8-4745-41a8-9d97-b91c66e50851.jpg)

Clicking locations the various fields stop being responsive:
![Screenshot 2023-05-03 at 12 07 45](https://user-images.githubusercontent.com/5323259/235888286-16dbace4-88fd-4385-a1d8-4c91c8f8673c.jpg)

Drag the browser window larger and smaller and notice how the various field go outside when locations is open (edit).

I am using a test site.
WordPress 6.2
Brave browser.

**Comment by joedolson** [comment]
This appears to be fixed; didn't test in Brave, but closing for now.
