### ISSUE TITLE
Repetition pattern not showing up in add events. 

### ISSUE THREAD

**Issue by Sunrisenews** [joedolson/my-calendar-pro#70]
**Describe the bug**
I do not appear to have the option to schedule recurring events. I've looked through the documentation and followed all the steps described in it, but at the point where I should see a place to add a repetition pattern, there is nothing there. I'll include a photo. 

**To Reproduce**
1. Go to add event.
2. Scroll down to Date and Time
3. See error

**Expected behavior**
I thought that I could add a repetition pattern after I entered in my date and time. 

**Screenshots**
![image](https://github.com/joedolson/my-calendar-pro/assets/140783056/04912c94-7caa-435f-a6b9-28ee3e10e65c)**Desktop (please complete the following information):**
OS: Windows 11
Browser Edge
Version 115.0.1901.203

**Additional context**

**Comment by joedolson** [comment]
Are Repetition Patterns enabled in your input settings? Go to My Calendar > Settings > Input and see whether 'Repetition Pattern' is checked. If it is, also go to My Calendar > Add Event, then click on 'Screen Options' in the upper right corner to see whether they're enabled for you, specifically.

**Comment by Sunrisenews** [comment]
Ah, that was it, thanks! It's working fine now.

**Comment by joedolson** [comment]
Great! Glad to hear it.
